import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://bonds-client-test.downinglabs.co.uk/');
  await page.getByRole('link', { name: 'Sign up' }).click();
  await page.locator('#register-titles-list').selectOption('4: Mr');
  await page.locator('#register-first-name-txt').click();
  await page.locator('#register-first-name-txt').fill('Harold');
  await page.locator('#register-first-name-txt').press('Tab');
  await page.locator('#register-last-name-txt').click();
  await page.locator('#register-last-name-txt').fill('Wilson');
  await page.locator('#register-email-txt').click();
  await page.locator('#register-email-txt').fill('haroldwilson@test.com');
  await page.locator('#register-phone-number-txt').click();
  await page.locator('#register-phone-number-txt').fill('01159123456');
  await page.locator('#register-how-you-heard-list').selectOption('4: Word of mouth');
  await page.getByRole('checkbox', { name: 'Yes, by email' }).check();
  await page.getByRole('button', { name: 'Sign up' }).click();
  await page.locator('#register-date-of-birth-day-list').selectOption('12: 12');
  await page.locator('#register-date-of-birth-month-list').selectOption('6: 6');
  await page.locator('#register-date-of-birth-year-list').selectOption('8: 2000');
  await page.getByRole('button', { name: 'Sign up' }).click();
  await page.locator('register span').nth(1).click();
  await page.getByRole('button', { name: 'Sign up' }).click();
  await page.goto('https://bonds-client-test.downinglabs.co.uk/account/personal-details/investor-type');
  await page.getByText('Certified Sophisticated', { exact: true }).click();
  await page.getByRole('radio', { name: 'Yes' }).check();
  await page.getByRole('radio', { name: 'No' }).check();
  await page.getByRole('checkbox', { name: 'None of these apply to me' }).check();
  await page.getByText('High Net Worth').click();
  await page.locator('#high-net-worth-has-sufficient-income-yes-radio').check();
  await page.locator('#high-net-worth-sufficient-income-amount-txt').click();
  await page.locator('#high-net-worth-sufficient-income-amount-txt').fill('1000000');
  await page.locator('#high-net-worth-sufficient-income-amount-txt').click();
  await page.locator('#high-net-worth-has-sufficient-net-assets-yes-radio').check();
  await page.locator('#high-net-worth-sufficient-net-assets-amount-txt').click();
  await page.locator('#high-net-worth-sufficient-net-assets-amount-txt').fill('199998');
  await page.locator('#high-net-worth-sufficient-net-assets-amount-txt').click();
  await page.locator('#high-net-worth-sufficient-net-assets-amount-txt').dblclick();
  await page.locator('#high-net-worth-sufficient-net-assets-amount-txt').fill('2000000');
  await page.locator('#declarations-investor-name-txt').click();
  await page.locator('#declarations-investor-name-txt').fill('Harold Wilson');
  await page.getByRole('button', { name: 'Open Calendar' }).click();
  await page.getByText('15', { exact: true }).click();
  await page.getByRole('button', { name: 'Open Calendar' }).click();
  await page.getByText('15', { exact: true }).click({
    button: 'right'
  });
  await page.locator('div').filter({ hasText: 'High Net Worth Certified' }).nth(2).click();
  await page.getByRole('combobox').selectOption('1: Business ownership');
  await page.getByRole('checkbox', { name: 'I understand the level of' }).check();
  await page.getByRole('checkbox', { name: 'If I were to lose the capital' }).check();
  await page.getByRole('checkbox', { name: 'I have sufficient assets and/' }).check();
  await page.getByRole('checkbox', { name: 'I confirm that any funds' }).check();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('radio', { name: 'An investment that is a kind' }).check();
  await page.getByRole('radio', { name: 'Yes, this is an investment,' }).check();
  await page.getByRole('radio', { name: 'No, there is no guarantee' }).check();
  await page.getByRole('radio', { name: 'No, whilst the bond is' }).check();
  await page.getByRole('radio', { name: 'No, I should spread my money' }).check();
  await page.getByRole('radio', { name: 'No, I recognise that Downing' }).check();
  await page.getByRole('radio', { name: 'False' }).check();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.goto('https://bonds-client-test.downinglabs.co.uk/restricted-access-orders');
  await expect(page.getByRole('heading', { name: 'Restricted access' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Hello Harold' })).toBeVisible();
  await page.getByRole('link', { name: 'Profile settings' }).click();
  await expect(page.getByRole('heading', { name: 'Email address: haroldwilson@' })).toBeVisible();
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').fill('ABC123!!gh');
  await page.getByRole('button', { name: 'Set Password' }).click();
  await expect(page.getByRole('heading', { name: 'Your password has been set' })).toBeVisible();
  await page.getByRole('link', { name: 'Log out' }).click();
});